# All Configurations
#-------------------
# Run Configurations
run_config:
  run_name: run2
  base_url: https://www.kannadaprabha.com/
  website_enum: 'kannadaprabha' # Website identifier
  website_base_dir: /home/ubuntu/work/darshan/kn-work/kannadaprabha/run2/websites/www.kannadaprabha.com/
  filter_domains:
    - 'kannadaprabha'

# To store the URLs
url_index:
  index: run2_seed_urls
  host: localhost
  port: 9200

article_index:
  index: run2_articles_v2
  host: localhost
  port: 9200

index_dump_conf:
  dump_file_path: /home/ubuntu/work/darshan/kn-work/dumps/run2_kannadaprabha.jl

log_config:
  level: 'WARNING' # Possible values: 'WARNING', 'INFO', 'DEBUG'
  error_log_file: 'logs/run2_error.log'
