# All Configurations
#-------------------
# Run Configurations
run_config:
  run_name: run3
  base_url: https://www.prajavani.net/
  website_enum: 'prajavani' # Website identifier
  website_base_dir: /home/ubuntu/work/darshan/kn-work/prajavani/run3/websites/www.prajavani.net/
  filter_domains:
    - 'prajavani'

# To store the URLs
url_index:
  index: run3_seed_urls
  host: localhost
  port: 9200

article_index:
  index: run3_articles_v2
  host: localhost
  port: 9200

index_dump_conf:
  dump_file_path: /home/ubuntu/work/darshan/kn-work/dumps/run3_prajavani.jl

log_config:
  level: 'WARNING' # Possible values: 'WARNING', 'INFO', 'DEBUG'
  error_log_file: 'logs/run3_error.log'
