# All Configurations

#----------
# Test config
elastic_test:
  index: test123
  doc_type: urls
  host: localhost
  port: 9200

#----------
# Run Configurations
run_config:
  run_name: run1
  base_url: https://www.kannadaprabha.com/
  website_base_dir: /home/adiga/my_work/kannada-news-dataset/crawling/snapshot_download/kannadaprabha/run1/websites/www.kannadaprabha.com/
  filter_domains:
    - 'kannadaprabha'

# To store the URLs
url_index:
  index: run1_seed_urls
  doc_type: url
  host: localhost
  port: 9200

log_config:
  level: 'DEBUG' # Possible values: 'WARNING', 'INFO', 'DEBUG'